/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankDetails {
  'ifscCode' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export type Blob = Uint8Array;
export interface PaymentRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'accepted' : null } |
    { 'declined' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : bigint,
}
export interface Submission {
  'id' : bigint,
  'status' : TaskStatus,
  'userId' : Principal,
  'file' : Blob,
  'createdAt' : bigint,
  'taskId' : bigint,
}
export interface Task { 'id' : bigint, 'title' : string, 'image' : [] | [Blob] }
export type TaskStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface UserProfile {
  'bankDetails' : [] | [BankDetails],
  'coinBalance' : bigint,
  'isBlocked' : boolean,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoins' : ActorMethod<[Principal, bigint], undefined>,
  'adminUpdateBankDetails' : ActorMethod<
    [Principal, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'deductCoins' : ActorMethod<[Principal, bigint], undefined>,
  'freezeAccountForCheat' : ActorMethod<[Principal], undefined>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getAllUsersAnalytics' : ActorMethod<
    [],
    Array<
      {
        'userId' : Principal,
        'tasksCompleted' : bigint,
        'email' : string,
        'totalSubmissions' : bigint,
        'lastLogin' : [] | [bigint],
      }
    >
  >,
  'getBankDetails' : ActorMethod<[Principal], [] | [BankDetails]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[Principal], bigint>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserAnalytics' : ActorMethod<
    [Principal],
    {
      'tasksCompleted' : bigint,
      'totalSubmissions' : bigint,
      'lastLogin' : [] | [bigint],
    }
  >,
  'getUserPayments' : ActorMethod<[Principal], Array<PaymentRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[Principal], Array<Submission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordLastLogin' : ActorMethod<[], undefined>,
  'requestPayment' : ActorMethod<[bigint], undefined>,
  'reviewPayment' : ActorMethod<[bigint, boolean], undefined>,
  'reviewSubmission' : ActorMethod<[bigint, boolean], undefined>,
  'saveBankDetails' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [{ 'isBlocked' : boolean, 'role' : string, 'email' : string }],
    undefined
  >,
  'submitTask' : ActorMethod<[bigint, Blob], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateTask' : ActorMethod<[bigint, string, [] | [Blob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];