/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Blob = IDL.Vec(IDL.Nat8);
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'userId' : IDL.Principal,
  'file' : Blob,
  'createdAt' : IDL.Int,
  'taskId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'coinBalance' : IDL.Nat,
  'isBlocked' : IDL.Bool,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'image' : IDL.Opt(Blob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'deductCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAllUsersAnalytics' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'userId' : IDL.Principal,
            'tasksCompleted' : IDL.Nat,
            'email' : IDL.Text,
            'totalSubmissions' : IDL.Nat,
            'lastLogin' : IDL.Opt(IDL.Int),
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserAnalytics' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'tasksCompleted' : IDL.Nat,
          'totalSubmissions' : IDL.Nat,
          'lastLogin' : IDL.Opt(IDL.Int),
        }),
      ],
      ['query'],
    ),
  'getUserPayments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLastLogin' : IDL.Func([], [], []),
  'requestPayment' : IDL.Func([IDL.Nat], [], []),
  'reviewPayment' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'reviewSubmission' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'isBlocked' : IDL.Bool,
          'role' : IDL.Text,
          'email' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'submitTask' : IDL.Func([IDL.Nat, Blob], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(Blob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'accepted' : IDL.Null,
      'declined' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Blob = IDL.Vec(IDL.Nat8);
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'userId' : IDL.Principal,
    'file' : Blob,
    'createdAt' : IDL.Int,
    'taskId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'coinBalance' : IDL.Nat,
    'isBlocked' : IDL.Bool,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'image' : IDL.Opt(Blob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'deductCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAllUsersAnalytics' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'userId' : IDL.Principal,
              'tasksCompleted' : IDL.Nat,
              'email' : IDL.Text,
              'totalSubmissions' : IDL.Nat,
              'lastLogin' : IDL.Opt(IDL.Int),
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserAnalytics' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'tasksCompleted' : IDL.Nat,
            'totalSubmissions' : IDL.Nat,
            'lastLogin' : IDL.Opt(IDL.Int),
          }),
        ],
        ['query'],
      ),
    'getUserPayments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLastLogin' : IDL.Func([], [], []),
    'requestPayment' : IDL.Func([IDL.Nat], [], []),
    'reviewPayment' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'reviewSubmission' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'isBlocked' : IDL.Bool,
            'role' : IDL.Text,
            'email' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'submitTask' : IDL.Func([IDL.Nat, Blob], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(Blob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };